# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sip_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sip_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11sip_service.proto\x12\nsipservice\"6\n\x0b\x43\x61llRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65stination\x18\x02 \x01(\t\"G\n\x0c\x43\x61llResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07\x63\x61ll_id\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t\" \n\rHangupRequest\x12\x0f\n\x07\x63\x61ll_id\x18\x01 \x01(\t\"8\n\x0eHangupResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\"A\n\nAudioChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x03 \x01(\x05\"-\n\x18\x45ventSubscriptionRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"X\n\tCallEvent\x12\x0f\n\x07\x63\x61ll_id\x18\x01 \x01(\t\x12)\n\nevent_type\x18\x02 \x01(\x0e\x32\x15.sipservice.EventType\x12\x0f\n\x07\x64\x65tails\x18\x03 \x01(\t*h\n\tEventType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x10\n\x0c\x43\x41LL_RINGING\x10\x01\x12\x14\n\x10\x43\x41LL_ESTABLISHED\x10\x02\x12\x13\n\x0f\x43\x41LL_TERMINATED\x10\x03\x12\x11\n\rINCOMING_CALL\x10\x04\x32\xa3\x02\n\nSipService\x12=\n\x08MakeCall\x12\x17.sipservice.CallRequest\x1a\x18.sipservice.CallResponse\x12?\n\x06Hangup\x12\x19.sipservice.HangupRequest\x1a\x1a.sipservice.HangupResponse\x12\x41\n\x0bStreamAudio\x12\x16.sipservice.AudioChunk\x1a\x16.sipservice.AudioChunk(\x01\x30\x01\x12R\n\x11SubscribeToEvents\x12$.sipservice.EventSubscriptionRequest\x1a\x15.sipservice.CallEvent0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sip_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENTTYPE']._serialized_start=458
  _globals['_EVENTTYPE']._serialized_end=562
  _globals['_CALLREQUEST']._serialized_start=33
  _globals['_CALLREQUEST']._serialized_end=87
  _globals['_CALLRESPONSE']._serialized_start=89
  _globals['_CALLRESPONSE']._serialized_end=160
  _globals['_HANGUPREQUEST']._serialized_start=162
  _globals['_HANGUPREQUEST']._serialized_end=194
  _globals['_HANGUPRESPONSE']._serialized_start=196
  _globals['_HANGUPRESPONSE']._serialized_end=252
  _globals['_AUDIOCHUNK']._serialized_start=254
  _globals['_AUDIOCHUNK']._serialized_end=319
  _globals['_EVENTSUBSCRIPTIONREQUEST']._serialized_start=321
  _globals['_EVENTSUBSCRIPTIONREQUEST']._serialized_end=366
  _globals['_CALLEVENT']._serialized_start=368
  _globals['_CALLEVENT']._serialized_end=456
  _globals['_SIPSERVICE']._serialized_start=565
  _globals['_SIPSERVICE']._serialized_end=856
# @@protoc_insertion_point(module_scope)
