# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sip_service_pb2 as sip__service__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sip_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SipServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MakeCall = channel.unary_unary(
                '/sipservice.SipService/MakeCall',
                request_serializer=sip__service__pb2.CallRequest.SerializeToString,
                response_deserializer=sip__service__pb2.CallResponse.FromString,
                _registered_method=True)
        self.Hangup = channel.unary_unary(
                '/sipservice.SipService/Hangup',
                request_serializer=sip__service__pb2.HangupRequest.SerializeToString,
                response_deserializer=sip__service__pb2.HangupResponse.FromString,
                _registered_method=True)
        self.StreamAudio = channel.stream_stream(
                '/sipservice.SipService/StreamAudio',
                request_serializer=sip__service__pb2.AudioChunk.SerializeToString,
                response_deserializer=sip__service__pb2.AudioChunk.FromString,
                _registered_method=True)
        self.SubscribeToEvents = channel.unary_stream(
                '/sipservice.SipService/SubscribeToEvents',
                request_serializer=sip__service__pb2.EventSubscriptionRequest.SerializeToString,
                response_deserializer=sip__service__pb2.CallEvent.FromString,
                _registered_method=True)


class SipServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MakeCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Hangup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAudio(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeToEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SipServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MakeCall': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeCall,
                    request_deserializer=sip__service__pb2.CallRequest.FromString,
                    response_serializer=sip__service__pb2.CallResponse.SerializeToString,
            ),
            'Hangup': grpc.unary_unary_rpc_method_handler(
                    servicer.Hangup,
                    request_deserializer=sip__service__pb2.HangupRequest.FromString,
                    response_serializer=sip__service__pb2.HangupResponse.SerializeToString,
            ),
            'StreamAudio': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamAudio,
                    request_deserializer=sip__service__pb2.AudioChunk.FromString,
                    response_serializer=sip__service__pb2.AudioChunk.SerializeToString,
            ),
            'SubscribeToEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeToEvents,
                    request_deserializer=sip__service__pb2.EventSubscriptionRequest.FromString,
                    response_serializer=sip__service__pb2.CallEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sipservice.SipService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sipservice.SipService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SipService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MakeCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sipservice.SipService/MakeCall',
            sip__service__pb2.CallRequest.SerializeToString,
            sip__service__pb2.CallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Hangup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sipservice.SipService/Hangup',
            sip__service__pb2.HangupRequest.SerializeToString,
            sip__service__pb2.HangupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamAudio(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/sipservice.SipService/StreamAudio',
            sip__service__pb2.AudioChunk.SerializeToString,
            sip__service__pb2.AudioChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeToEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sipservice.SipService/SubscribeToEvents',
            sip__service__pb2.EventSubscriptionRequest.SerializeToString,
            sip__service__pb2.CallEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
